import pandas as pd
import plotly.express as px
import streamlit as st
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parents[1]
OUTPUT_DIR = BASE_DIR / "outputs"


@st.cache_data(show_spinner=False)
def load_csv(name: str, parse_dates=None) -> pd.DataFrame:
    path = OUTPUT_DIR / name
    if not path.exists():
        raise FileNotFoundError(
            f"{path} not found. Run `python quick_analysis.py` from the repo root first."
        )
    return pd.read_csv(path, parse_dates=parse_dates)


def main():
    st.set_page_config(
        page_title="Facilities Operations Insights",
        layout="wide",
        initial_sidebar_state="expanded",
    )
    st.title("Facilities Operations Insights")
    st.caption(
        "Data source: CSV exports generated by `quick_analysis.py` "
        "(orders, KPIs, and pipeline logs)."
    )

    daily_rev = load_csv("daily_revenue.csv", parse_dates=["order_date"])
    weekly_rev = load_csv("weekly_revenue.csv", parse_dates=["week_start"])
    region_rev = load_csv("revenue_by_region.csv")
    segment_rev = load_csv("revenue_by_segment.csv")
    category_rev = load_csv("revenue_by_category.csv")
    region_segment = load_csv("revenue_region_segment.csv")
    segment_category = load_csv("segment_category_mix.csv")
    top_products = load_csv("top_products.csv")
    kpis = load_csv("daily_kpis_enriched.csv", parse_dates=["date"])
    weekday_gap = load_csv("weekday_gap.csv")
    discount = load_csv("discount_impact.csv")
    ops_latency = load_csv("ops_latency.csv")
    ops_failures = load_csv("ops_failures.csv")
    ops_hourly = load_csv("ops_hourly.csv")

    total_revenue = daily_rev["revenue_usd"].sum()
    total_orders = int(daily_rev["orders_count"].sum())
    avg_order_value = total_revenue / total_orders
    hit_rate = (kpis["orders_count"] >= kpis["orders_target"]).mean()
    avg_gap = kpis["target_gap"].mean()
    weekend_gap = (
        kpis[kpis["date"].dt.day_name().isin(["Sunday", "Monday"])]["target_gap"].mean()
    )
    failure_totals = ops_failures.set_index("job").get("failure", pd.Series()).sum()

    col1, col2, col3, col4, col5 = st.columns(5)
    col1.metric("Total Revenue (USD)", f"{total_revenue:,.0f}")
    col2.metric("Orders", f"{total_orders:,}")
    col3.metric("Avg Order Value", f"{avg_order_value:,.0f}")
    col4.metric("Target Hit Rate", f"{hit_rate:.0%}", f"{avg_gap:+.1f} avg gap")
    col5.metric("Weekend Gap", f"{weekend_gap:+.1f}", "Sun & Mon")

    st.subheader("Demand Trends")
    merged = (
        daily_rev.merge(
            kpis[["date", "orders_target"]],
            left_on="order_date",
            right_on="date",
            how="left",
        )
        .drop(columns=["date"])
        .rename(columns={"orders_count_x": "orders_count"})
    )
    trend_fig = px.line(
        merged,
        x="order_date",
        y=["revenue_usd", "orders_count", "orders_target"],
        labels={"value": "Value", "order_date": "Date", "variable": "Metric"},
    )
    trend_fig.update_layout(legend_title=None)
    st.plotly_chart(trend_fig, width="stretch")

    st.subheader("Revenue Mix")
    col_left, col_right = st.columns(2)
    region_fig = px.bar(
        region_rev,
        x="region",
        y="revenue_usd",
        title="Revenue by Region",
        labels={"revenue_usd": "Revenue (USD)", "region": "Region"},
    )
    col_left.plotly_chart(region_fig, width="stretch")

    category_fig = px.bar(
        category_rev,
        x="category",
        y="revenue_usd",
        title="Revenue by Category",
        labels={"revenue_usd": "Revenue (USD)", "category": "Category"},
    )
    col_right.plotly_chart(category_fig, width="stretch")

    heatmap_fig = px.imshow(
        region_segment.set_index("region"),
        aspect="auto",
        labels=dict(color="Revenue (USD)"),
        title="Region vs Segment Heatmap",
    )
    st.plotly_chart(heatmap_fig, width="stretch")

    mix_fig = px.bar(
        segment_category,
        x="segment",
        y="revenue_usd",
        color="category",
        title="Segment x Category Mix",
        labels={"revenue_usd": "Revenue (USD)", "segment": "Segment"},
    )
    st.plotly_chart(mix_fig, width="stretch")

    st.subheader("KPI & Conversion Health")
    gap_fig = px.bar(
        weekday_gap.sort_values("target_gap"),
        x="weekday",
        y="target_gap",
        title="Average Target Gap by Weekday",
        labels={"target_gap": "Orders vs Target"},
    )
    st.plotly_chart(gap_fig, width="stretch")

    kpi_cols = st.columns(2)
    disc_fig = px.bar(
        discount,
        x="discount_flag",
        y="sum",
        title="Revenue Impact of Discounting",
        labels={"discount_flag": "Discount Applied", "sum": "Revenue (USD)"},
    )
    kpi_cols[0].plotly_chart(disc_fig, width="stretch")

    weekly_fig = px.line(
        weekly_rev,
        x="week_start",
        y=["revenue_usd", "orders_count", "discount_share"],
        title="Weekly Revenue, Orders, and Discount Share",
        labels={"week_start": "Week Start", "value": "Value", "variable": "Metric"},
    )
    kpi_cols[1].plotly_chart(weekly_fig, width="stretch")

    st.subheader("Operational Reliability")
    ops_cols = st.columns([2, 1])
    failure_heatmap = px.density_heatmap(
        ops_hourly,
        x="hour",
        y="job",
        z="failure_rate",
        title="Failure Rate by Job and Hour",
        color_continuous_scale="Reds",
        labels={"failure_rate": "Failure Rate"},
    )
    ops_cols[0].plotly_chart(failure_heatmap, width="stretch")

    latency_fig = px.bar(
        ops_latency,
        x="job",
        y="mean",
        error_y=ops_latency["max"] - ops_latency["mean"],
        title="Average Latency per Job",
        labels={"mean": "Avg Latency (s)", "job": "Job"},
    )
    ops_cols[1].plotly_chart(latency_fig, width="stretch")

    st.subheader("Top Products (by Revenue)")
    st.dataframe(
        top_products[
            [
                "product_id",
                "order_category",
                "catalog_category",
                "revenue_usd",
                "orders",
                "unit_price_usd",
            ]
        ].rename(
            columns={
                "order_category": "order_category (from sales)",
                "catalog_category": "catalog_category",
            }
        ),
        hide_index=True,
        width="stretch",
    )


if __name__ == "__main__":
    main()

